# Generated by Django 4.0.4 on 2022-05-16 05:10

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='EMail')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='UserName')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='last Name')),
                ('kids_count', models.IntegerField(default=0, verbose_name='Kids Count')),
                ('facebook', models.CharField(blank=True, max_length=300, null=True, verbose_name='Facebook')),
                ('instagram', models.CharField(blank=True, max_length=300, null=True, verbose_name='Instagram')),
                ('pinterest', models.CharField(blank=True, max_length=300, null=True, verbose_name='Pinterest')),
                ('snapchat', models.CharField(blank=True, max_length=300, null=True, verbose_name='Snapchat')),
                ('linkedin', models.CharField(blank=True, max_length=300, null=True, verbose_name='LinkedIn')),
                ('twitter', models.CharField(blank=True, max_length=300, null=True, verbose_name='Twitter')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('staff', models.BooleanField(default=False, verbose_name='Is Staff')),
                ('admin', models.BooleanField(default=False, verbose_name='Is Admin')),
                ('superuser', models.BooleanField(default=False, verbose_name='Is SuperUser')),
                ('image', models.ImageField(default=accounts.models.default_image, upload_to=accounts.models.upload_account_image, verbose_name='Image')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-date_updated', '-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='ShippingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Home', 'Home'), ('Work', 'Work')], max_length=255)),
                ('mobile', models.IntegerField(blank=True, null=True, verbose_name='Mobile')),
                ('country', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('floor', models.IntegerField()),
                ('flat', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
