# Generated by Django 4.0.4 on 2022-05-16 05:20

from django.db import migrations, models
import django.db.models.deletion
import toys.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, default=toys.models.default_image, null=True, upload_to=toys.models.upload_category_image, verbose_name='Image')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='toys.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('sku', models.IntegerField(verbose_name='SKU')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description')),
                ('barcode', models.IntegerField(verbose_name='Barcode')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Weight')),
                ('height', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Height')),
                ('length', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Length')),
                ('width', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Width')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price')),
                ('age', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Age')),
                ('inventory', models.IntegerField(verbose_name='Inventory')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('image', models.ImageField(blank=True, default=toys.models.default_image, null=True, upload_to=toys.models.upload_toy_image, verbose_name='Image')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toys.category', verbose_name='Category')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
